# Generated by Django 5.1.1 on 2024-09-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_id', models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('TI', 'Tarjeta de identidad'), ('CE', 'Cédula de extranjería'), ('RC', 'Registro civil'), ('PA', 'Pasaporte'), ('AS', 'Adulto sin identificación'), ('MS', 'Menor sin identificación'), ('NU', 'Número único de identificación'), ('NV', 'Certificado de nacido vivo'), ('SC', 'Salvoconducto'), ('NIT', 'Nit'), ('CD', 'Carnet diplomático'), ('PE', 'Permiso especial de permanencia'), ('RE', 'Residente especial para la paz'), ('PT', 'Permiso por protección temporal'), ('DE', 'Documento extranjero')], max_length=100)),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=1)),
                ('numero_identificacion', models.CharField(max_length=20)),
                ('Nombres', models.CharField(max_length=100)),
                ('Apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('email', models.EmailField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
    ]
